export const BUSINESS_TRIP_PREFIX = "BT";

export const BUSINESS_TRIP_STATUS = {
    DRAFT: "Draft",
    SUBMITTED: "Diajukan",
    PENDING_APPROVAL: "Menunggu Approval",
    REJECTED: "Ditolak",
    APPROVED: "Disetujui",
    ADVANCE_DISBURSED: "Uang Muka Dicairkan",
    IN_PROGRESS: "Perjalanan Berlangsung",
    REALIZATION_DRAFT: "Draft Laporan Realisasi",
    REALIZATION_SUBMITTED: "Menunggu Verifikasi Realisasi",
    REALIZATION_REVISION_REQUIRED: "Perbaikan Realisasi",
    REALIZATION_VERIFIED: "Realisasi Terverifikasi",
    PENDING_REFUND: "Menunggu Pengembalian",
    PENDING_ADDITIONAL_PAYMENT: "Menunggu Pembayaran Kekurangan",
    COMPLETED: "Selesai",
};

export const BUSINESS_TRIP_STATUS_FLOW = [
    BUSINESS_TRIP_STATUS.DRAFT,
    BUSINESS_TRIP_STATUS.SUBMITTED,
    BUSINESS_TRIP_STATUS.PENDING_APPROVAL,
    BUSINESS_TRIP_STATUS.APPROVED,
    BUSINESS_TRIP_STATUS.ADVANCE_DISBURSED,
    BUSINESS_TRIP_STATUS.IN_PROGRESS,
    BUSINESS_TRIP_STATUS.REALIZATION_DRAFT,
    BUSINESS_TRIP_STATUS.REALIZATION_SUBMITTED,
    BUSINESS_TRIP_STATUS.REALIZATION_REVISION_REQUIRED,
    BUSINESS_TRIP_STATUS.REALIZATION_VERIFIED,
    BUSINESS_TRIP_STATUS.PENDING_REFUND,
    BUSINESS_TRIP_STATUS.PENDING_ADDITIONAL_PAYMENT,
    BUSINESS_TRIP_STATUS.COMPLETED,
];

export const BUSINESS_TRIP_STATUS_LABELS = {
    [BUSINESS_TRIP_STATUS.DRAFT]: "Draft",
    [BUSINESS_TRIP_STATUS.SUBMITTED]: "Diajukan",
    [BUSINESS_TRIP_STATUS.PENDING_APPROVAL]: "Menunggu Approval",
    [BUSINESS_TRIP_STATUS.REJECTED]: "Ditolak",
    [BUSINESS_TRIP_STATUS.APPROVED]: "Disetujui",
    [BUSINESS_TRIP_STATUS.ADVANCE_DISBURSED]: "Uang Muka Dicairkan",
    [BUSINESS_TRIP_STATUS.IN_PROGRESS]: "Perjalanan Berlangsung",
    [BUSINESS_TRIP_STATUS.REALIZATION_DRAFT]: "Draft Laporan Realisasi",
    [BUSINESS_TRIP_STATUS.REALIZATION_SUBMITTED]:
        "Menunggu Verifikasi Realisasi",
    [BUSINESS_TRIP_STATUS.REALIZATION_REVISION_REQUIRED]: "Perbaikan Realisasi",
    [BUSINESS_TRIP_STATUS.REALIZATION_VERIFIED]: "Realisasi Terverifikasi",
    [BUSINESS_TRIP_STATUS.PENDING_REFUND]: "Menunggu Pengembalian",
    [BUSINESS_TRIP_STATUS.PENDING_ADDITIONAL_PAYMENT]:
        "Menunggu Pembayaran Kekurangan",
    [BUSINESS_TRIP_STATUS.COMPLETED]: "Selesai",
};

export const NEXT_BUSINESS_TRIP_STATUS = {
    [BUSINESS_TRIP_STATUS.DRAFT]: BUSINESS_TRIP_STATUS.SUBMITTED,
    [BUSINESS_TRIP_STATUS.SUBMITTED]: BUSINESS_TRIP_STATUS.PENDING_APPROVAL,
    [BUSINESS_TRIP_STATUS.PENDING_APPROVAL]: BUSINESS_TRIP_STATUS.APPROVED,
    [BUSINESS_TRIP_STATUS.APPROVED]: BUSINESS_TRIP_STATUS.ADVANCE_DISBURSED,
    [BUSINESS_TRIP_STATUS.ADVANCE_DISBURSED]: BUSINESS_TRIP_STATUS.IN_PROGRESS,
    [BUSINESS_TRIP_STATUS.IN_PROGRESS]: BUSINESS_TRIP_STATUS.REALIZATION_DRAFT,
    [BUSINESS_TRIP_STATUS.REALIZATION_DRAFT]:
        BUSINESS_TRIP_STATUS.REALIZATION_SUBMITTED,
    [BUSINESS_TRIP_STATUS.REALIZATION_SUBMITTED]:
        BUSINESS_TRIP_STATUS.REALIZATION_VERIFIED,
    [BUSINESS_TRIP_STATUS.REALIZATION_REVISION_REQUIRED]:
        BUSINESS_TRIP_STATUS.REALIZATION_DRAFT,
    [BUSINESS_TRIP_STATUS.REALIZATION_VERIFIED]:
        BUSINESS_TRIP_STATUS.COMPLETED,
    [BUSINESS_TRIP_STATUS.PENDING_REFUND]: BUSINESS_TRIP_STATUS.COMPLETED,
    [BUSINESS_TRIP_STATUS.PENDING_ADDITIONAL_PAYMENT]:
        BUSINESS_TRIP_STATUS.COMPLETED,
};

export const canTransitionBusinessTripStatus = (currentStatus, nextStatus) =>
    NEXT_BUSINESS_TRIP_STATUS[currentStatus] === nextStatus ||
    (currentStatus === BUSINESS_TRIP_STATUS.PENDING_APPROVAL &&
        nextStatus === BUSINESS_TRIP_STATUS.REJECTED) ||
    (currentStatus === BUSINESS_TRIP_STATUS.REJECTED &&
        nextStatus === BUSINESS_TRIP_STATUS.SUBMITTED);

export const getStatusTone = (status) => {
    if (status === BUSINESS_TRIP_STATUS.DRAFT) return "slate";
    if (status === BUSINESS_TRIP_STATUS.REJECTED) return "red";
    if (
        status === BUSINESS_TRIP_STATUS.PENDING_APPROVAL ||
        status === BUSINESS_TRIP_STATUS.REALIZATION_SUBMITTED ||
        status === BUSINESS_TRIP_STATUS.PENDING_REFUND ||
        status === BUSINESS_TRIP_STATUS.PENDING_ADDITIONAL_PAYMENT
    ) {
        return "amber";
    }
    if (
        status === BUSINESS_TRIP_STATUS.APPROVED ||
        status === BUSINESS_TRIP_STATUS.COMPLETED
    ) {
        return "green";
    }
    return "sky";
};

export const isRealizationAvailable = (status) =>
    [
        BUSINESS_TRIP_STATUS.IN_PROGRESS,
        BUSINESS_TRIP_STATUS.REALIZATION_DRAFT,
        BUSINESS_TRIP_STATUS.REALIZATION_REVISION_REQUIRED,
        BUSINESS_TRIP_STATUS.REALIZATION_SUBMITTED,
        BUSINESS_TRIP_STATUS.PENDING_REFUND,
        BUSINESS_TRIP_STATUS.PENDING_ADDITIONAL_PAYMENT,
        BUSINESS_TRIP_STATUS.COMPLETED,
    ].includes(status);
