-- A single bank transfer may settle multiple approved reimbursements for the
-- same requester. The batch is the audit record; every linked reimbursement
-- keeps the same proof URL for backwards-compatible list and report views.
create table if not exists public.reimbursement_payment_batches (
    id uuid primary key default gen_random_uuid(),
    batch_number bigint generated by default as identity unique not null,
    requester_id uuid not null references public.profiles(id) on delete restrict,
    total_amount numeric(14, 2) not null check (total_amount > 0),
    transfer_proof_url text not null check (btrim(transfer_proof_url) <> ''),
    paid_by uuid not null references public.profiles(id) on delete restrict,
    paid_at timestamptz not null default now(),
    created_at timestamptz not null default now()
);

alter table public.reimbursements
    add column if not exists payment_batch_id uuid
        references public.reimbursement_payment_batches(id) on delete restrict;

create index if not exists reimbursements_payment_batch_id_idx
    on public.reimbursements (payment_batch_id);

alter table public.reimbursements
    drop constraint if exists reimbursements_payment_batch_status_check,
    add constraint reimbursements_payment_batch_status_check
        check (payment_batch_id is null or payment_status = 'paid');

alter table public.reimbursement_payment_batches enable row level security;

drop policy if exists "Users can read related reimbursement payment batches"
    on public.reimbursement_payment_batches;
create policy "Users can read related reimbursement payment batches"
on public.reimbursement_payment_batches
for select
to authenticated
using (
    requester_id = auth.uid()
    or exists (
        select 1
        from public.profiles profile
        where profile.id = auth.uid()
          and profile.role in ('admin', 'management')
    )
);

grant select on public.reimbursement_payment_batches to authenticated;

-- Keep the row-level reimbursement state valid when a batch link is added.
create or replace function public.validate_reimbursement_update()
returns trigger
language plpgsql
as $$
declare
    is_integrity_repair boolean := coalesce(
        current_setting('app.reimbursement_integrity_repair', true),
        ''
    ) = 'true';
    payment_batch public.reimbursement_payment_batches%rowtype;
begin
    if new.requester_id <> old.requester_id
        or new.transaction_date <> old.transaction_date
        or new.claim_amount <> old.claim_amount
        or new.description <> old.description
        or new.created_at <> old.created_at then
        raise exception 'Data pengajuan reimburse tidak boleh diubah setelah submit.';
    end if;

    if is_integrity_repair then
        return new;
    end if;

    if new.approved_amount is not null
        and (new.approved_amount <= 0 or new.approved_amount > new.claim_amount) then
        raise exception 'Nominal disetujui harus lebih dari 0 dan tidak boleh melebihi nominal klaim.';
    end if;

    if new.status = 'pending' then
        if new.approved_amount is not null
            or new.approved_by is not null
            or new.approved_at is not null
            or new.transfer_proof_url is not null
            or new.payment_batch_id is not null
            or new.paid_by is not null
            or new.paid_at is not null
            or new.payment_status <> 'unpaid' then
            raise exception 'Reimbursement pending tidak boleh memiliki data approval atau pembayaran.';
        end if;
        return new;
    end if;

    if new.status = 'rejected' then
        if coalesce(new.rejection_reason, '') = '' then
            raise exception 'Alasan penolakan wajib diisi.';
        end if;
        if new.approved_by is null or new.approved_at is null then
            raise exception 'Data penolakan tidak lengkap.';
        end if;
        if new.approved_amount is not null
            or new.approval_note is not null
            or new.transfer_proof_url is not null
            or new.payment_batch_id is not null
            or new.paid_by is not null
            or new.paid_at is not null
            or new.payment_status <> 'unpaid' then
            raise exception 'Reimbursement ditolak tidak boleh memiliki data pembayaran.';
        end if;
        return new;
    end if;

    if new.status <> 'approved' then
        raise exception 'Status reimburse tidak valid.';
    end if;

    if new.approved_amount is null
        or new.approved_amount <= 0
        or new.approved_amount > new.claim_amount then
        raise exception 'Nominal disetujui wajib lebih dari 0 dan tidak boleh melebihi nominal klaim.';
    end if;
    if new.approved_by is null or new.approved_at is null then
        raise exception 'Data approval tidak lengkap.';
    end if;

    if old.status = 'pending' then
        if new.payment_status <> 'unpaid'
            or new.transfer_proof_url is not null
            or new.payment_batch_id is not null
            or new.paid_by is not null
            or new.paid_at is not null then
            raise exception 'Approval dan pembayaran reimbursement harus diproses terpisah.';
        end if;
        return new;
    end if;

    if old.status <> 'approved' and not is_integrity_repair then
        raise exception 'Reimburse yang sudah diproses tidak dapat diubah.';
    end if;

    if new.approved_amount is distinct from old.approved_amount
        or new.approval_note is distinct from old.approval_note
        or new.approved_by is distinct from old.approved_by
        or new.approved_at is distinct from old.approved_at
        or new.rejection_reason is distinct from old.rejection_reason
        or new.status is distinct from old.status then
        raise exception 'Data approval reimbursement yang sudah final tidak dapat diubah.';
    end if;

    if old.payment_status <> 'unpaid' then
        raise exception 'Reimbursement yang sudah dibayar tidak dapat diubah.';
    end if;
    if new.payment_status <> 'paid'
        or coalesce(new.transfer_proof_url, '') = ''
        or new.payment_batch_id is null
        or new.paid_by is null
        or new.paid_at is null then
        raise exception 'Pembayaran reimbursement wajib memiliki status paid, bukti transfer batch, dan data pembayaran.';
    end if;

    select *
    into payment_batch
    from public.reimbursement_payment_batches as batch
    where batch.id = new.payment_batch_id;
    if not found
        or payment_batch.requester_id <> new.requester_id
        or payment_batch.transfer_proof_url <> new.transfer_proof_url
        or payment_batch.paid_by <> new.paid_by
        or payment_batch.paid_at <> new.paid_at then
        raise exception 'Data reimbursement harus sesuai dengan batch pembayaran yang terhubung.';
    end if;

    return new;
end;
$$;

create or replace function public.mark_reimbursement_batch_paid(
    p_reimbursement_ids uuid[],
    p_transfer_proof_url text
)
returns table (
    id uuid,
    batch_number bigint,
    requester_id uuid,
    total_amount numeric,
    transfer_proof_url text,
    paid_by uuid,
    paid_at timestamptz
)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    v_actor_id uuid := auth.uid();
    v_role text;
    v_item_count integer;
    v_requester_count integer;
    v_requester_id uuid;
    v_total_amount numeric(14, 2);
    v_paid_at timestamptz := now();
    v_batch public.reimbursement_payment_batches%rowtype;
begin
    if v_actor_id is null then
        raise exception 'Sesi pengguna tidak ditemukan.';
    end if;
    if coalesce(cardinality(p_reimbursement_ids), 0) = 0 then
        raise exception 'Pilih minimal satu reimbursement untuk dibayar.';
    end if;
    if cardinality(p_reimbursement_ids) <> (
        select count(distinct reimbursement_id)
        from unnest(p_reimbursement_ids) as selected(reimbursement_id)
    ) then
        raise exception 'Daftar reimbursement pembayaran memuat item duplikat.';
    end if;
    if coalesce(btrim(p_transfer_proof_url), '') = '' then
        raise exception 'Bukti transfer wajib diupload.';
    end if;

    select lower(coalesce(profile.role, ''))
    into v_role
    from public.profiles as profile
    where profile.id = v_actor_id;
    if coalesce(v_role, '') not in ('admin', 'management') then
        raise exception 'Hanya admin atau management yang dapat mencatat pembayaran reimbursement.';
    end if;

    -- Lock selected rows before validating, so two payment attempts cannot pay
    -- the same reimbursement or create overlapping batches.
    perform 1
    from public.reimbursements as reimbursement
    where reimbursement.id = any(p_reimbursement_ids)
    order by reimbursement.id
    for update;

    select
        count(*),
        count(distinct reimbursement.requester_id),
        coalesce(sum(reimbursement.approved_amount), 0)
    into v_item_count, v_requester_count, v_total_amount
    from public.reimbursements as reimbursement
    where reimbursement.id = any(p_reimbursement_ids)
      and reimbursement.status = 'approved'
      and reimbursement.payment_status = 'unpaid';

    if v_item_count <> cardinality(p_reimbursement_ids) then
        raise exception 'Sebagian reimbursement sudah berubah status atau tidak dapat dibayar. Muat ulang data lalu coba lagi.';
    end if;
    if v_requester_count <> 1 then
        raise exception 'Satu batch pembayaran hanya boleh berisi reimbursement dari satu pengaju.';
    end if;

    select reimbursement.requester_id
    into v_requester_id
    from public.reimbursements as reimbursement
    where reimbursement.id = any(p_reimbursement_ids)
    limit 1;

    insert into public.reimbursement_payment_batches (
        requester_id,
        total_amount,
        transfer_proof_url,
        paid_by,
        paid_at
    )
    values (
        v_requester_id,
        v_total_amount,
        p_transfer_proof_url,
        v_actor_id,
        v_paid_at
    )
    returning * into v_batch;

    update public.reimbursements as reimbursement
    set payment_status = 'paid',
        transfer_proof_url = p_transfer_proof_url,
        payment_batch_id = v_batch.id,
        paid_by = v_actor_id,
        paid_at = v_paid_at
    where reimbursement.id = any(p_reimbursement_ids)
      and reimbursement.status = 'approved'
      and reimbursement.payment_status = 'unpaid';

    return query
    select
        v_batch.id,
        v_batch.batch_number,
        v_batch.requester_id,
        v_batch.total_amount,
        v_batch.transfer_proof_url,
        v_batch.paid_by,
        v_batch.paid_at;
end;
$$;

revoke all on function public.mark_reimbursement_batch_paid(uuid[], text) from public;
grant execute on function public.mark_reimbursement_batch_paid(uuid[], text)
    to authenticated;

notify pgrst, 'reload schema';
